- name: Install a list of packages for pdf-parser
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python3
    - python3-pip
    - poppler-utils

# Install (Bottle) python package.
- name: Install (Bottle) python package. 
  pip:
    executable: pip3
    name: pdfminer.six
